// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAWyXNHD4XGHGRCwFK4L6QQ9dtffYDwcs',
    appId: '1:186468891275:web:7e59972bc48b35c1a7f28e',
    messagingSenderId: '186468891275',
    projectId: 'searchengine-c740c',
    authDomain: 'searchengine-c740c.firebaseapp.com',
    storageBucket: 'searchengine-c740c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdPHB32Ri2DRjCjOrpE7WHrxK7RXHSxpQ',
    appId: '1:186468891275:android:ee2bed0953d8e338a7f28e',
    messagingSenderId: '186468891275',
    projectId: 'searchengine-c740c',
    storageBucket: 'searchengine-c740c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEl2RSFI1OAIu3ZzFJdKBaWAxXkjVVy8w',
    appId: '1:186468891275:ios:794aff18c00bf18fa7f28e',
    messagingSenderId: '186468891275',
    projectId: 'searchengine-c740c',
    storageBucket: 'searchengine-c740c.appspot.com',
    iosClientId: '186468891275-g5gakcu760q2vsrn0j593o485us7benj.apps.googleusercontent.com',
    iosBundleId: 'com.example.kwicApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEl2RSFI1OAIu3ZzFJdKBaWAxXkjVVy8w',
    appId: '1:186468891275:ios:794aff18c00bf18fa7f28e',
    messagingSenderId: '186468891275',
    projectId: 'searchengine-c740c',
    storageBucket: 'searchengine-c740c.appspot.com',
    iosClientId: '186468891275-g5gakcu760q2vsrn0j593o485us7benj.apps.googleusercontent.com',
    iosBundleId: 'com.example.kwicApp',
  );
}
